version: 2
jobs:
  build:
    docker:
      - image: basaks/passive-seismic:0.2
    working_directory: /usr/src/passive-seismic
    steps:
      - checkout
      - run: mkdir -p test_output/pytest test_output/flake8 test_output/coverage
      - run: pip install .[dev]
      # - run: make lint
      - run: make coverage
      - store_artifacts:
          path: test_output/coverage
          destination: reports
      - store_test_results:
          path: test_output/