inputs:
  - name: my miniseed files
    type: miniseed
    files:
      # - directory: # not supported yet
      - file: tests/mocks/data/ev0_6.a01.gse2
      - file: tests/mocks/data/ev0_6.a02.gse2
      # - list: # not supported yet
  # events and time based functionality only available inside SC3
  - name: my events
    type: events
    events:
      - event_id: ga2017abcdefg
      - event_id: ga2017hijklmn
      # - event_id_list: # not supported yet

  - name: my time range
    type: time # not supported yet
    times:
      start_time:
      end_time:
